services:
  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: fitprogress
      MARIADB_USER: fitprogress
      MARIADB_PASSWORD: fitprogress
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 5
      start_period: 60s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: fitprogress
      PMA_PASSWORD: fitprogress
    depends_on:
      - database

volumes:
  database_data: